// Universal types
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';

// Image Library types
export const SET_QUERY = 'SET_QUERY';
export const GET_RESULTS = 'GET_RESULTS';
export const SET_CURRENT = 'SET_CURRENT';
export const GET_CURRENT_MANIFEST = 'GET_CURRENT_MANIFEST';

// EPIC types
export const GET_MOST_RECENT_NATURAL_METADATA =
  'GET_MOST_RECENT_NATURAL_METADATA';
export const GET_MOST_RECENT_ENHANCED_METADATA =
  'GET_MOST_RECENT_ENHANCED_METADATA';
export const SET_TYPE = 'SET_TYPE';
export const SET_CURRENT_METADATA = 'SET_CURRENT_METADATA';
export const GET_NATURAL_METADATA_BY_DATE = 'GET_NATURAL_METADATA_BY_DATE';
export const GET_ENHANCED_METADATA_BY_DATE = 'GET_ENHANCED_METADATA_BY_DATE';
